### ISSUE TITLE
You have to consume all of stdin

### ISSUE THREAD

**Issue by tjconcept** [pull-stream/stream-to-pull-stream#10]
If you do not consume everything of `stdin` (for instance using `pull.take`) an error is thrown:

```
Error: write EPIPE
    at exports._errnoException (util.js:1026:11)
    at WriteWrap.afterWrite (net.js:799:14)
```

**Comment by dominictarr** [comment]
I'm a bit confused about you did to cause this error. can you show post code to reproduce this?

**Comment by tjconcept** [comment]
Sorry about that, it was an error earlier in the pipeline revealed by `pull.take` (https://github.com/mafintosh/csv-parser/issues/61).
