### ISSUE TITLE
Abort assumes close event

### ISSUE THREAD

**Issue by skeggse** [pull-stream/stream-to-pull-stream#12]
When you abort a readable stream using stream-to-pull-stream, [we assume](https://github.com/pull-stream/stream-to-pull-stream/blob/master/index.js#L175-L178) the underlying Node-style stream will emit an `close` event. This is not always the case, and [not required](https://nodejs.org/api/stream.html#stream_event_close_1) by the docs. I do think streams should emit the `close` event in this case, though, given the new `destroy` docs [claim](https://nodejs.org/api/stream.html#stream_readable_destroy_error) that it will emit the `close` event.

I'm just bringing this up in case you have a good idea on how to fix this. I'm attempting to fix this issue upstream too (by having the stream in question emit the `close` event).

**Comment by dominictarr** [comment]
I think it's a far better idea for streams to emit close consistently. Even before I went to pull-streams, I argued that node streams should consider close to be mandatory. All core streams have close, and so do streams created via through/through2 and the base classes in node. I'd consider that a defacto standard.

**Comment by skeggse** [comment]
Agreed, thanks for the feedback!
