### ISSUE TITLE
Promise support

### ISSUE THREAD

**Issue by tjconcept** [pull-stream/stream-to-pull-stream#13]
1. What do you think of adding support for promises in this library, such that a sink returns a promise if no callback is supplied?
2. Would you accept a PR implementing it?

My rough idea for an implementation is along the lines of:

```js
let p
if (!cb) {
  p = new Promise((resolve, reject) => {
    cb = err => err ? reject(err) : resolve()
  })
}

[existing code]

return p
```

**Comment by dominictarr** [comment]
not interested. if you want promises, make a wrapper module.
