### ISSUE TITLE
Uncaught TypeError: stream.destroy is not a function

### ISSUE THREAD

**Issue by dignifiedquire** [pull-stream/stream-to-pull-stream#9]
In https://github.com/pull-stream/stream-to-pull-stream/blob/master/index.js#L156 it is assumed that the stream has a `destroy` method, but some streams do not have those. This results for me in 

```
Uncaught TypeError: stream.destroy is not a function
      at node_modules/stream-to-pull-stream/index.js:156:14
```

**Comment by dominictarr** [comment]
Ah. Yeah we should not crash if that happens.

However, I would also _strongly encourage_ streams to implement `destroy`. It's not listed as a mandatory in the official node docs, but if you read between the lines, `destroy` is essential. most node streams implement it (I've never seen this error until now ;)
especially if they inherit from through or through2.

**Comment by dominictarr** [comment]
not implementing destroy means it's possible you'll have a [resource leak](https://github.com/nodejs/node/issues/1834) pull-streams don't have this problem, but you are using `stream-to-pull-stream` without destroy, then you'll get resource leaks.

**Comment by dominictarr** [comment]
I fixed this in 1.6.9
it won't crash, but it will log a warning.

**Comment by dignifiedquire** [comment]
Thanks :)

**Comment by yoshuawuyts** [comment]
Side note on `stream.destroy()`; WG def wants to implement this in Node core, but is writing regression tests for existing functionality first so when it's added, it doesn't break like everything around it. No specific ETA though hey

**Comment by dominictarr** [comment]
I thought that all core node streams (except stdio) had `destroy`? which ones dont?

**Comment by yoshuawuyts** [comment]
@dominictarr none do - it's something `through2` has, and widely regarded as necessary, but not yet part of [any of the constructors exposed by Node core](https://nodejs.org/api/stream.html).

**Comment by dominictarr** [comment]
Oh right, got it.
All the actual core streams node creates, net, fs, etc, etc all have destroy.

I was saying this was a defacto requirement since like, way back before streams2 even...

**Comment by yoshuawuyts** [comment]
lol what - I wasn't aware haha - that sounds... not good 🌵

**Comment by dominictarr** [comment]
Yeah, well, that is why it's on `through2`, because `through2` inherited it from `through`, which had `destroy` since the initial commit https://github.com/dominictarr/through/commit/903501acf73d03f584dd572b885c78c1bc9cca8b way back in 2012!

**Comment by yoshuawuyts** [comment]
haha, oh shit - yeah thanks for sharing the history! There'll be a good amount of streams WG folks hanging out in Ams around Sept; hopefully we can make node core streams catch up to 2012 then :grin:

**Comment by dominictarr** [comment]
oh cool. I'll be around for nodeconf.eu was planning on coming through AMS also.

**Comment by yoshuawuyts** [comment]
yeah, cool! - should totes hang :tada:
